#!/bin/bash
#
#  Copyright (C) 2018 Gaël PORTAY
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# docker-compose build --build-arg USER=$USER --build-arg UID=$UID --build-arg GID=${GROUPS[0]} irc
# docker-compose up --name "$0-$USER" --rm -d

name="${0##*/}-$USER"
cid="$(docker ps -qf "name=$name")"
if ! [[ $cid ]]
then
	echo "service $name down!"
	echo "Please run \$ systemctl start weechat@$USER.service"
	exit
fi >&2

exec docker attach "$name"
