#!/bin/bash
#
#  Copyright (C) 2019 Gaël PORTAY
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ $# -lt 2 ]
then
	cat <<EOF
Usage: ${0##*/} USER DIR 

Update the relay.pem file of WeeChat.

USER is the owner and DIR is the path to the privkey.pem and fullchain.pem
files.

Example:
	\$ ${0##/*} "${SUDO_USER:-$USER}" /etc/letsencrypt/live/vps.portay.io-0001/
EOF
	exit 1
fi

umask 077
cat "$2/"{privkey.pem,fullchain.pem} >"/data/weechat/$1/ssl/relay.pem"
chown "$1:$1" "/data/weechat/$1/ssl/relay.pem"
exec su "$1" -c "echo '*/relay sslcertkey' >/data/weechat/$1/weechat_fifo"
