version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=999
      - USER_GID=998
    restart: always
    networks:
      - gitea
    volumes:
      - /data/gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
