web:
  image: nginx
  volumes:
    - /data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - /data/nginx/certs:/etc/nginx/certs:ro 
    - /data/nginx/html:/usr/share/nginx/html:ro
    - /etc/letsencrypt/:/etc/letsencrypt:ro 
  ports:
    - "80:80"
    - "443:443"
  command: [nginx-debug, '-g', 'daemon off;']
