version: "2"

services:
  irc:
    container_name: weechat-$USER
    build:
      context: .
      args:
        USER: $USER
        UID: $UID
        GID: $GROUPS
    volumes:
      - /data/weechat/$USER:/home/$USER/.weechat
    ports:
      - "9000:9000"
      - "9001:9001"
    stdin_open: true
    tty: true
